# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HPoZJBy8jkICP6uUtmcfLwgLLn2ufuh
"""

import altair as alt
import pandas as pd

df = pd.read_excel("edades_2014_2024.xlsx")

# Agregar total por grupo
df_total = df.groupby("grupo_edad")["siniestros_totales"].sum().reset_index()

chart = alt.Chart(df_total).mark_bar(
    cornerRadiusTopLeft=4,
    cornerRadiusTopRight=4
).encode(
    x=alt.X("grupo_edad:N", title="Grupo etario"),
    y=alt.Y("siniestros_totales:Q", title="Siniestros 2014–2024"),
    color=alt.condition(
        alt.datum.grupo_edad == "30-44",
        alt.value("#FFD21F"),      # amarillo de alerta
        alt.value("#6A7B8A")       # azul-gris manual
    ),
    tooltip=["grupo_edad","siniestros_totales"]
).properties(
    title="Exposición al riesgo por edad",
    width=500,
    height=350
)

chart

df = pd.read_excel("horas_2014_2024.xlsx")

df_total = df.groupby("franja")["siniestros"].sum().reset_index()
df_total["franja"] = pd.Categorical(df_total["franja"],
    ["00:00-02:59","03:00-05:59","06:00-08:59",
     "09:00-11:59","12:00-14:59","15:00-17:59",
     "18:00-20:59","21:00-23:59"],
    ordered=True)

chart = alt.Chart(df_total).mark_area(
    interpolate="monotone",
    opacity=0.3,
    color="#FFD21F"
).encode(
    x=alt.X("franja:N", title="Horario del día"),
    y=alt.Y("siniestros:Q", title="Siniestros acumulados"),
    tooltip=["franja","siniestros"]
).properties(
    title="Horas con mayor riesgo de siniestros ferroviarios",
    width=550
)

chart

import altair as alt
import pandas as pd

# Cargar archivo
df = pd.read_excel("horas_2014_2024.xlsx")

# Orden correcto de las franjas
orden_franjas = [
    "00:00-02:59",
    "03:00-05:59",
    "06:00-08:59",
    "09:00-11:59",
    "12:00-14:59",
    "15:00-17:59",
    "18:00-20:59",
    "21:00-23:59"
]

# Asegurar que la columna franja esté ordenada
df["franja"] = pd.Categorical(df["franja"], orden_franjas, ordered=True)

# Totales por franja
df_total = df.groupby("franja")["siniestros"].sum().reset_index()

# Clasificación estadística
mean = df_total["siniestros"].mean()
std = df_total["siniestros"].std()

def nivel(x):
    if x > mean + 0.5*std:
        return "Alta incidencia"
    elif x < mean - 0.5*std:
        return "Baja incidencia"
    else:
        return "Incidencia media"

df_total["nivel"] = df_total["siniestros"].apply(nivel)

# Colores según identidad visual
colors = alt.Scale(
    domain=["Alta incidencia","Incidencia media","Baja incidencia"],
    range=["#FFD21F", "#6A7B8A", "#C6CDD3"]  # amarillo – azul – gris
)

# Línea base
linea = alt.Chart(df_total).mark_line(
    stroke="#6A7B8A",
    strokeWidth=2
).encode(
    x=alt.X("franja:N", title="Franja horaria"),
    y=alt.Y("siniestros:Q", title="Siniestros acumulados"),
)

# Puntos clasificados
puntos = alt.Chart(df_total).mark_circle(size=200).encode(
    x="franja:N",
    y="siniestros:Q",
    color=alt.Color("nivel:N", scale=colors, title="Nivel de incidencia"),
    tooltip=["franja","siniestros","nivel"]
)

chart = (linea + puntos).properties(
    title="Riesgo ferroviario por franja horaria (2014–2024)",
    width=650,
    height=380
)

chart