# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Z6HVf05fTRvci9i7RUGINsIG8dmihkO
"""

# 1. Importar librerías
import pandas as pd

# 2. Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 3. Definir rutas de los CSV
ruta_base = "/Base_unificada.csv"
ruta_edad = "/Por_Edad.csv"
ruta_horario = "/Por_Horario.csv"
ruta_dia = "/Por_Dia.csv"

# 4. Cargar cada archivo en un DataFrame
df_base = pd.read_csv(ruta_base)
df_edad = pd.read_csv(ruta_edad)
df_horario = pd.read_csv(ruta_horario)
df_dia = pd.read_csv(ruta_dia)

# 5. Mostrar las primeras filas de cada base
print("Base unificada:")
display(df_base.head())

print("\nPor Edad:")
display(df_edad.head())

print("\nPor Horario:")
display(df_horario.head())

print("\nPor Día:")
display(df_dia.head())