# -*- coding: utf-8 -*-
"""Visualización 1 Base de datos limpia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FZ_BCuxT-61juxab93fm1pqJzwaDusIs

# **Entrega 02: Integrante Andrés Hernández**
"""

import pandas as pd

# Cargar y revisar el archivo
file_path = '/content/drive/MyDrive/NARRACIÓN GRÁFICA/BASES DE DATOS/Señalización EFE.csv'
# file_path = '/content/drive/MyDrive/NARRACIÓN GRÁFICA/BASES DE DATOS/Señalización EFE.csv'

#Cambio en el formato del archivo para su visualización
data = pd.read_csv(file_path, encoding='latin-1')

# Dividir los datos en columnas usando el delimitador ';'
data = pd.read_csv(file_path, encoding='latin1', delimiter=';')

# Mostrar las primeras filas para verificar la estructura
data.head()