# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ShZSO-a47Br6YxuAl1PIrGtTKbj7mmz
"""

import pandas as pd

df2=pd.read_csv("/datoslimpios1.csv")

df2